// <auto-generated/>

// This is needed to make the T4 templates build as they are targeting .NET Framework in Rider

namespace System.Runtime.Remoting.Messaging;

public static class CallContext
{
    public static object LogicalGetData(string key)
    {
        return null;
    }
}