// <auto-generated/>

// This is needed to make the T4 templates build as they are targeting .NET Framework in Rider

namespace System.Runtime.Remoting.Messaging;

/// <summary>Provides the call-context surface required when compiling the T4 templates.</summary>
public static class CallContext
{
    /// <summary>Gets logical call-context data for the specified key.</summary>
    /// <param name="key">The name of the data item.</param>
    /// <returns>The stored data, or <see langword="null"/> when no data is available.</returns>
    public static object LogicalGetData(string key)
    {
        return null;
    }
}