//<auto-generated />

using System.Diagnostics.CodeAnalysis;

namespace System.Text;

// Keep this type in every target because netstandard consumers compile static calls to it, but a higher-targeted app can bind them to the net10 FastData.Generator assembly at runtime.

[SuppressMessage("Roslynator", "RCS1197:Optimize StringBuilder.Append/AppendLine call")]
public static class StringBuilderCompat
{
    extension(StringBuilder sb)
    {
        public StringBuilder AppendJoin<T>(string? separator, IEnumerable<T> values) => sb.Append(string.Join(separator, values));
    }
}