//<auto-generated />

#if NETSTANDARD2_0
using System.Diagnostics.CodeAnalysis;

namespace System.Text;

[SuppressMessage("Roslynator", "RCS1197:Optimize StringBuilder.Append/AppendLine call")]
public static class StringBuilderCompat
{
    extension(StringBuilder sb)
    {
        public StringBuilder AppendJoin<T>(string? separator, IEnumerable<T> values) => sb.Append(string.Join(separator, values));
    }
}
#endif