//<auto-generated />
#nullable enable

using System.Diagnostics.CodeAnalysis;

namespace System.Text;

// Keep this type in every target because netstandard consumers compile static calls to it, but a higher-targeted app can bind them to the net10 FastData.Generator assembly at runtime.

/// <summary>Provides string-builder APIs required by consumers targeting older frameworks.</summary>
[SuppressMessage("Roslynator", "RCS1197:Optimize StringBuilder.Append/AppendLine call")]
public static class StringBuilderCompat
{
    extension(StringBuilder sb)
    {
        /// <summary>Appends the string representations of values separated by the specified delimiter.</summary>
        /// <typeparam name="T">The value type.</typeparam>
        /// <param name="separator">The separator placed between values.</param>
        /// <param name="values">The values to append.</param>
        /// <returns>The string builder after the values have been appended.</returns>
        public StringBuilder AppendJoin<T>(string? separator, IEnumerable<T> values) => sb.Append(string.Join(separator, values));
    }
}