//<auto-generated />

#if NETSTANDARD2_0

using System.Numerics;

namespace System;

/// <summary>Polyfill for Int128 (available in .NET 7+). This is intentionally limited to the operations FastData needs.</summary>
internal readonly struct Int128 : IComparable<Int128>, IEquatable<Int128>
{
    private static readonly BigInteger TwoPow64 = BigInteger.One << 64;
    private static readonly BigInteger TwoPow128 = BigInteger.One << 128;

    private readonly ulong _lower;
    private readonly ulong _upper;

    public Int128(ulong upper, ulong lower)
    {
        _lower = lower;
        _upper = upper;
    }

    public int CompareTo(Int128 other)
    {
        if (this < other)
            return -1;
        if (this > other)
            return 1;
        return 0;
    }

    public bool Equals(Int128 other) => this == other;

    public override bool Equals(object? obj) => obj is Int128 other && Equals(other);

    public override int GetHashCode()
    {
        unchecked
        {
            return (_lower.GetHashCode() * 397) ^ _upper.GetHashCode();
        }
    }

    public static implicit operator Int128(byte value) => new Int128(0, value);

    public static implicit operator Int128(sbyte value)
    {
        long lower = value;
        return new Int128((ulong)(lower >> 63), (ulong)lower);
    }

    public static implicit operator Int128(short value)
    {
        long lower = value;
        return new Int128((ulong)(lower >> 63), (ulong)lower);
    }

    public static implicit operator Int128(ushort value) => new Int128(0, value);

    public static implicit operator Int128(int value)
    {
        long lower = value;
        return new Int128((ulong)(lower >> 63), (ulong)lower);
    }

    public static implicit operator Int128(uint value) => new Int128(0, value);

    public static implicit operator Int128(long value) => new Int128((ulong)(value >> 63), (ulong)value);

    public static implicit operator Int128(ulong value) => new Int128(0, value);

    public static explicit operator Int128(double value) => FromBigInteger(new BigInteger(value));

    public static explicit operator sbyte(Int128 value) => (sbyte)value._lower;

    public static explicit operator byte(Int128 value) => (byte)value._lower;

    public static explicit operator short(Int128 value) => (short)value._lower;

    public static explicit operator ushort(Int128 value) => (ushort)value._lower;

    public static explicit operator int(Int128 value) => (int)value._lower;

    public static explicit operator uint(Int128 value) => (uint)value._lower;

    public static explicit operator long(Int128 value) => (long)value._lower;

    public static explicit operator ulong(Int128 value) => value._lower;

    public static explicit operator float(Int128 value) => (float)value.ToBigInteger();

    public static explicit operator double(Int128 value) => (double)value.ToBigInteger();

    public static Int128 operator +(Int128 left, Int128 right)
    {
        ulong lower = left._lower + right._lower;
        ulong carry = lower < left._lower ? 1UL : 0UL;
        ulong upper = left._upper + right._upper + carry;
        return new Int128(upper, lower);
    }

    public static Int128 operator -(Int128 left, Int128 right) => left + (-right);

    public static Int128 operator -(Int128 value) => ~value + 1;

    public static Int128 operator *(Int128 left, Int128 right) => FromBigInteger(left.ToBigInteger() * right.ToBigInteger());

    public static Int128 operator /(Int128 left, Int128 right) => FromBigInteger(left.ToBigInteger() / right.ToBigInteger());

    public static Int128 operator ~(Int128 value) => new Int128(~value._upper, ~value._lower);

    public static bool operator ==(Int128 left, Int128 right) => left._lower == right._lower && left._upper == right._upper;

    public static bool operator !=(Int128 left, Int128 right) => left._lower != right._lower || left._upper != right._upper;

    public static bool operator <(Int128 left, Int128 right) => (long)left._upper < (long)right._upper || (left._upper == right._upper && left._lower < right._lower);

    public static bool operator >(Int128 left, Int128 right) => (long)left._upper > (long)right._upper || (left._upper == right._upper && left._lower > right._lower);

    public static bool operator <=(Int128 left, Int128 right) => (long)left._upper < (long)right._upper || (left._upper == right._upper && left._lower <= right._lower);

    public static bool operator >=(Int128 left, Int128 right) => (long)left._upper > (long)right._upper || (left._upper == right._upper && left._lower >= right._lower);

    private static Int128 FromBigInteger(BigInteger value)
    {
        value %= TwoPow128;
        if (value < BigInteger.Zero)
            value += TwoPow128;

        BigInteger upper = value >> 64;
        BigInteger lower = value & (TwoPow64 - BigInteger.One);
        return new Int128((ulong)upper, (ulong)lower);
    }

    private BigInteger ToBigInteger()
    {
        BigInteger value = (new BigInteger(_upper) << 64) + _lower;
        if ((long)_upper < 0)
            value -= TwoPow128;
        return value;
    }
}

#endif
