//<auto-generated />

#if NETSTANDARD2_0

namespace System;

/// <summary>Polyfill for Math.BitIncrement and MathF.BitIncrement (available in .NET Core 3.0+).</summary>
internal static class MathCompat
{
    public static float BitIncrement(float x)
    {
        if (float.IsNaN(x) || float.IsPositiveInfinity(x))
            return x;

        if (x == 0f)
            return float.Epsilon;

        int bits = BitConverter.ToInt32(BitConverter.GetBytes(x), 0);
        bits = x > 0 ? bits + 1 : bits - 1;
        return BitConverter.ToSingle(BitConverter.GetBytes(bits), 0);
    }

    public static double BitIncrement(double x)
    {
        if (double.IsNaN(x) || double.IsPositiveInfinity(x))
            return x;

        if (x == 0d)
            return double.Epsilon;

        long bits = BitConverter.DoubleToInt64Bits(x);
        bits = x > 0 ? bits + 1 : bits - 1;
        return BitConverter.Int64BitsToDouble(bits);
    }

    public static float BitDecrement(float x)
    {
        if (float.IsNaN(x) || float.IsNegativeInfinity(x))
            return x;

        if (x == 0f)
            return -float.Epsilon;

        int bits = BitConverter.ToInt32(BitConverter.GetBytes(x), 0);
        bits = x > 0 ? bits - 1 : bits + 1;
        return BitConverter.ToSingle(BitConverter.GetBytes(bits), 0);
    }

    public static double BitDecrement(double x)
    {
        if (double.IsNaN(x) || double.IsNegativeInfinity(x))
            return x;

        if (x == 0d)
            return -double.Epsilon;

        long bits = BitConverter.DoubleToInt64Bits(x);
        bits = x > 0 ? bits - 1 : bits + 1;
        return BitConverter.Int64BitsToDouble(bits);
    }
}

#endif